package edu.usc.imsc.spatial.building;

import java.math.BigDecimal;

/**
 * Buildings generated by hbm2java
 */
public class Buildings {

	private BigDecimal id;
	private String name;
	private String shortname;
	private String address;
	private String lon;
	private String lat;
	
	public Buildings(BigDecimal id, String name, String shortname,
			String address, String lon, String lat) {
		super();
		this.id = id;
		this.name = name;
		this.shortname = shortname;
		this.address = address;
		this.lon = lon;
		this.lat = lat;
	}
	
	public BigDecimal getId() {
		return id;
	}
	public void setId(BigDecimal id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getShortname() {
		return shortname;
	}
	public void setShortname(String shortname) {
		this.shortname = shortname;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getLon() {
		return lon;
	}
	public void setLon(String lon) {
		this.lon = lon;
	}
	public String getLat() {
		return lat;
	}
	public void setLat(String lat) {
		this.lat = lat;
	}
}